FROM golang:1.13-buster as build
ENV GOPATH=/go
RUN apt-get update && apt-get install go-dep && \
    git clone https://github.com/improbable-eng/grpc-web.git $GOPATH/src/github.com/improbable-eng/grpc-web && \
    cd $GOPATH/src/github.com/improbable-eng/grpc-web && \
    dep ensure -v && \
    go install ./go/grpcwebproxy

FROM gcr.io/distroless/base-debian10
COPY --from=build /go/bin/grpcwebproxy /
EXPOSE 8080 8443
ENTRYPOINT ["/grpcwebproxy"]