apiVersion: v1
kind: Service
metadata:
  name: grpc-web-proxy
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 443
      name: https
      targetPort: 8443
    - protocol: TCP # debug
      port: 80
      name: http
      targetPort: 8080
