FROM golang:latest
RUN mkdir /app
COPY . /app/
WORKDIR /app
RUN go build -gcflags='all=-N -l' -o main .
ENV GOTRACEBACK=all
ENV GRPC_VERBOSITY=DEBUG
ENV GRPC_TRACE=all
ENV GODEBUG=http2debug=2
ENTRYPOINT ["/app/main"]
CMD ["-host", "0.0.0.0"]