apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: server
        env:
          - name: POSTGRES_DSN
            value: postgres://postgres:@dbsvc:5432/postgres?sslmode=disable
        ports:
          - containerPort: 10000
      - name: grpc-web-proxy
        image: grpcwebproxy
        args:
          - --backend_addr=localhost:10000
          - --run_tls_server=false
          - --allow_all_origins
        ports:
          - containerPort: 8443
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  selector:
    app: server
  ports:
    - port: 10000
      targetPort: 10000
      protocol: TCP
