apiVersion: apps/v1
kind: Deployment
metadata:
  name: daemon
  labels:
    app: daemon
spec:
  selector:
    matchLabels:
      app: daemon
  template:
    metadata:
      labels:
        app: daemon
    spec:
      securityContext:
        fsGroup: 2000
        runAsGroup: 2000
        runAsUser: 1000

      containers:
        - name: daemon
          image: daemon
          env:
            - name: SID_SERVER_DSN
              value: "tcp://server:10000"
            - name: ID_RSA_PATH
              value: "/config/id_rsa"
            - name: POLL_FREQUENCY_SECONDS
              value: "20"

          volumeMounts:
            - mountPath: "/config"
              name: config
              readOnly: true
            - mountPath: "/git-projects"
              name: repos
              readOnly: false
      volumes:
        - name: config
          secret:
            secretName: id-rsa
            items:
              - key: id_rsa
                path: id_rsa
        - name: repos
          emptyDir: {}