// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sid.proto

package sid

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HealthStatus_Status int32

const (
	HealthStatus_INACTIVE HealthStatus_Status = 0
	HealthStatus_READY    HealthStatus_Status = 1
	HealthStatus_WORKING  HealthStatus_Status = 2
	HealthStatus_LEAVING  HealthStatus_Status = 3
)

var HealthStatus_Status_name = map[int32]string{
	0: "INACTIVE",
	1: "READY",
	2: "WORKING",
	3: "LEAVING",
}

var HealthStatus_Status_value = map[string]int32{
	"INACTIVE": 0,
	"READY":    1,
	"WORKING":  2,
	"LEAVING":  3,
}

func (x HealthStatus_Status) String() string {
	return proto.EnumName(HealthStatus_Status_name, int32(x))
}

func (HealthStatus_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_923cdea5d0e24e4a, []int{0, 0}
}

type Job_JobStatus int32

const (
	Job_QUEUED    Job_JobStatus = 0
	Job_BUILDING  Job_JobStatus = 1
	Job_ABANDONED Job_JobStatus = 2
	Job_COMPLETED Job_JobStatus = 3
)

var Job_JobStatus_name = map[int32]string{
	0: "QUEUED",
	1: "BUILDING",
	2: "ABANDONED",
	3: "COMPLETED",
}

var Job_JobStatus_value = map[string]int32{
	"QUEUED":    0,
	"BUILDING":  1,
	"ABANDONED": 2,
	"COMPLETED": 3,
}

func (x Job_JobStatus) String() string {
	return proto.EnumName(Job_JobStatus_name, int32(x))
}

func (Job_JobStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_923cdea5d0e24e4a, []int{1, 0}
}

type JobRunEvent_EventType int32

const (
	JobRunEvent_RUN_LOG JobRunEvent_EventType = 0
	JobRunEvent_ERROR   JobRunEvent_EventType = 1
)

var JobRunEvent_EventType_name = map[int32]string{
	0: "RUN_LOG",
	1: "ERROR",
}

var JobRunEvent_EventType_value = map[string]int32{
	"RUN_LOG": 0,
	"ERROR":   1,
}

func (x JobRunEvent_EventType) String() string {
	return proto.EnumName(JobRunEvent_EventType_name, int32(x))
}

func (JobRunEvent_EventType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_923cdea5d0e24e4a, []int{2, 0}
}

// HealthStatus
type HealthStatus struct {
	Status               HealthStatus_Status  `protobuf:"varint,1,opt,name=status,proto3,enum=sid.HealthStatus_Status" json:"status,omitempty"`
	StatusAt             *timestamp.Timestamp `protobuf:"bytes,2,opt,name=status_at,json=statusAt,proto3" json:"status_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *HealthStatus) Reset()         { *m = HealthStatus{} }
func (m *HealthStatus) String() string { return proto.CompactTextString(m) }
func (*HealthStatus) ProtoMessage()    {}
func (*HealthStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_923cdea5d0e24e4a, []int{0}
}

func (m *HealthStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthStatus.Unmarshal(m, b)
}
func (m *HealthStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthStatus.Marshal(b, m, deterministic)
}
func (m *HealthStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthStatus.Merge(m, src)
}
func (m *HealthStatus) XXX_Size() int {
	return xxx_messageInfo_HealthStatus.Size(m)
}
func (m *HealthStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthStatus.DiscardUnknown(m)
}

var xxx_messageInfo_HealthStatus proto.InternalMessageInfo

func (m *HealthStatus) GetStatus() HealthStatus_Status {
	if m != nil {
		return m.Status
	}
	return HealthStatus_INACTIVE
}

func (m *HealthStatus) GetStatusAt() *timestamp.Timestamp {
	if m != nil {
		return m.StatusAt
	}
	return nil
}

type Job struct {
	RepoName             string               `protobuf:"bytes,1,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	RepoSshUrl           string               `protobuf:"bytes,2,opt,name=repo_ssh_url,json=repoSshUrl,proto3" json:"repo_ssh_url,omitempty"`
	CommitHexsha         string               `protobuf:"bytes,3,opt,name=commit_hexsha,json=commitHexsha,proto3" json:"commit_hexsha,omitempty"`
	JobStatus            Job_JobStatus        `protobuf:"varint,4,opt,name=job_status,json=jobStatus,proto3,enum=sid.Job_JobStatus" json:"job_status,omitempty"`
	StatusAt             *timestamp.Timestamp `protobuf:"bytes,5,opt,name=status_at,json=statusAt,proto3" json:"status_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_923cdea5d0e24e4a, []int{1}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetRepoName() string {
	if m != nil {
		return m.RepoName
	}
	return ""
}

func (m *Job) GetRepoSshUrl() string {
	if m != nil {
		return m.RepoSshUrl
	}
	return ""
}

func (m *Job) GetCommitHexsha() string {
	if m != nil {
		return m.CommitHexsha
	}
	return ""
}

func (m *Job) GetJobStatus() Job_JobStatus {
	if m != nil {
		return m.JobStatus
	}
	return Job_QUEUED
}

func (m *Job) GetStatusAt() *timestamp.Timestamp {
	if m != nil {
		return m.StatusAt
	}
	return nil
}

type JobRunEvent struct {
	Type                 JobRunEvent_EventType `protobuf:"varint,1,opt,name=type,proto3,enum=sid.JobRunEvent_EventType" json:"type,omitempty"`
	Content              string                `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	EventAt              *timestamp.Timestamp  `protobuf:"bytes,3,opt,name=event_at,json=eventAt,proto3" json:"event_at,omitempty"`
	Job                  *Job                  `protobuf:"bytes,4,opt,name=job,proto3" json:"job,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *JobRunEvent) Reset()         { *m = JobRunEvent{} }
func (m *JobRunEvent) String() string { return proto.CompactTextString(m) }
func (*JobRunEvent) ProtoMessage()    {}
func (*JobRunEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_923cdea5d0e24e4a, []int{2}
}

func (m *JobRunEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JobRunEvent.Unmarshal(m, b)
}
func (m *JobRunEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JobRunEvent.Marshal(b, m, deterministic)
}
func (m *JobRunEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JobRunEvent.Merge(m, src)
}
func (m *JobRunEvent) XXX_Size() int {
	return xxx_messageInfo_JobRunEvent.Size(m)
}
func (m *JobRunEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_JobRunEvent.DiscardUnknown(m)
}

var xxx_messageInfo_JobRunEvent proto.InternalMessageInfo

func (m *JobRunEvent) GetType() JobRunEvent_EventType {
	if m != nil {
		return m.Type
	}
	return JobRunEvent_RUN_LOG
}

func (m *JobRunEvent) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *JobRunEvent) GetEventAt() *timestamp.Timestamp {
	if m != nil {
		return m.EventAt
	}
	return nil
}

func (m *JobRunEvent) GetJob() *Job {
	if m != nil {
		return m.Job
	}
	return nil
}

type CheckInResponse struct {
	Response             string   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckInResponse) Reset()         { *m = CheckInResponse{} }
func (m *CheckInResponse) String() string { return proto.CompactTextString(m) }
func (*CheckInResponse) ProtoMessage()    {}
func (*CheckInResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_923cdea5d0e24e4a, []int{3}
}

func (m *CheckInResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckInResponse.Unmarshal(m, b)
}
func (m *CheckInResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckInResponse.Marshal(b, m, deterministic)
}
func (m *CheckInResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckInResponse.Merge(m, src)
}
func (m *CheckInResponse) XXX_Size() int {
	return xxx_messageInfo_CheckInResponse.Size(m)
}
func (m *CheckInResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckInResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckInResponse proto.InternalMessageInfo

func (m *CheckInResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func init() {
	proto.RegisterEnum("sid.HealthStatus_Status", HealthStatus_Status_name, HealthStatus_Status_value)
	proto.RegisterEnum("sid.Job_JobStatus", Job_JobStatus_name, Job_JobStatus_value)
	proto.RegisterEnum("sid.JobRunEvent_EventType", JobRunEvent_EventType_name, JobRunEvent_EventType_value)
	proto.RegisterType((*HealthStatus)(nil), "sid.HealthStatus")
	proto.RegisterType((*Job)(nil), "sid.Job")
	proto.RegisterType((*JobRunEvent)(nil), "sid.JobRunEvent")
	proto.RegisterType((*CheckInResponse)(nil), "sid.CheckInResponse")
}

func init() { proto.RegisterFile("sid.proto", fileDescriptor_923cdea5d0e24e4a) }

var fileDescriptor_923cdea5d0e24e4a = []byte{
	// 542 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0xc1, 0x92, 0xd2, 0x4c,
	0x10, 0x26, 0x64, 0x17, 0x92, 0x86, 0xfd, 0xff, 0x38, 0x7a, 0xa0, 0xe2, 0x41, 0x2a, 0x7b, 0x90,
	0x8b, 0xd9, 0x15, 0xcb, 0xf2, 0xe0, 0x29, 0x90, 0x14, 0x0b, 0x62, 0xd0, 0x01, 0xd6, 0xf2, 0x94,
	0x4a, 0x60, 0xdc, 0x80, 0x24, 0x93, 0xca, 0x0c, 0x96, 0xfb, 0x2a, 0x1e, 0x7d, 0x08, 0x5f, 0xc3,
	0x57, 0xb2, 0x66, 0x92, 0x20, 0xae, 0x56, 0x59, 0x1e, 0x92, 0x74, 0x7f, 0xf3, 0x65, 0xbe, 0xee,
	0xaf, 0x1b, 0x74, 0xb6, 0x59, 0xdb, 0x59, 0x4e, 0x39, 0x45, 0x2a, 0xdb, 0xac, 0xcd, 0x47, 0x37,
	0x94, 0xde, 0xec, 0xc8, 0x85, 0x84, 0xa2, 0xfd, 0x87, 0x0b, 0xbe, 0x49, 0x08, 0xe3, 0x61, 0x92,
	0x15, 0x2c, 0xeb, 0x9b, 0x02, 0xed, 0x2b, 0x12, 0xee, 0x78, 0x3c, 0xe7, 0x21, 0xdf, 0x33, 0x74,
	0x09, 0x0d, 0x26, 0xa3, 0x8e, 0xd2, 0x55, 0x7a, 0xff, 0xf5, 0x3b, 0xb6, 0xb8, 0xf2, 0x98, 0x62,
	0x17, 0x1f, 0x5c, 0xf2, 0xd0, 0x0b, 0xd0, 0x8b, 0x28, 0x08, 0x79, 0xa7, 0xde, 0x55, 0x7a, 0xad,
	0xbe, 0x69, 0x17, 0xba, 0x76, 0xa5, 0x6b, 0x2f, 0x2a, 0x5d, 0xac, 0x15, 0x64, 0x87, 0x5b, 0x2f,
	0xa1, 0x51, 0x8a, 0xb6, 0x41, 0x1b, 0xfb, 0xce, 0x70, 0x31, 0xbe, 0xf6, 0x8c, 0x1a, 0xd2, 0xe1,
	0x14, 0x7b, 0x8e, 0xfb, 0xde, 0x50, 0x50, 0x0b, 0x9a, 0xef, 0x66, 0xf8, 0xd5, 0xd8, 0x1f, 0x19,
	0x75, 0x91, 0x4c, 0x3d, 0xe7, 0x5a, 0x24, 0xaa, 0xf5, 0xa5, 0x0e, 0xea, 0x84, 0x46, 0xe8, 0x21,
	0xe8, 0x39, 0xc9, 0x68, 0x90, 0x86, 0x09, 0x91, 0x25, 0xeb, 0x58, 0x13, 0x80, 0x1f, 0x26, 0x04,
	0x75, 0xa1, 0x2d, 0x0f, 0x19, 0x8b, 0x83, 0x7d, 0xbe, 0x93, 0xd5, 0xe9, 0x18, 0x04, 0x36, 0x67,
	0xf1, 0x32, 0xdf, 0xa1, 0x73, 0x38, 0x5b, 0xd1, 0x24, 0xd9, 0xf0, 0x20, 0x26, 0x9f, 0x59, 0x1c,
	0x76, 0x54, 0x49, 0x69, 0x17, 0xe0, 0x95, 0xc4, 0xd0, 0x53, 0x80, 0x2d, 0x8d, 0x82, 0xd2, 0x97,
	0x13, 0xe9, 0x0b, 0x92, 0xbe, 0x4c, 0x68, 0x24, 0x9e, 0xd2, 0x11, 0x7d, 0x5b, 0x85, 0xbf, 0x9a,
	0x72, 0xfa, 0x0f, 0xa6, 0x0c, 0x41, 0x3f, 0x5c, 0x88, 0x00, 0x1a, 0x6f, 0x97, 0xde, 0xd2, 0x73,
	0x8d, 0x9a, 0xf0, 0x68, 0xb0, 0x1c, 0x4f, 0x5d, 0xd1, 0xbe, 0x82, 0xce, 0x40, 0x77, 0x06, 0x8e,
	0xef, 0xce, 0x7c, 0xcf, 0x35, 0xea, 0x22, 0x1d, 0xce, 0x5e, 0xbf, 0x99, 0x7a, 0x0b, 0xcf, 0x35,
	0x54, 0xeb, 0xbb, 0x02, 0xad, 0x09, 0x8d, 0xf0, 0x3e, 0xf5, 0x3e, 0x91, 0x94, 0x23, 0x1b, 0x4e,
	0xf8, 0x6d, 0x46, 0xca, 0x91, 0x9a, 0x55, 0xe9, 0xd5, 0xb9, 0x2d, 0xdf, 0x8b, 0xdb, 0x8c, 0x60,
	0xc9, 0x43, 0x1d, 0x68, 0xae, 0x68, 0xca, 0x49, 0xca, 0x4b, 0xcb, 0xaa, 0x14, 0x3d, 0x07, 0x8d,
	0x08, 0xb2, 0x68, 0x4b, 0xfd, 0x6b, 0x5b, 0x4d, 0xc9, 0x75, 0x38, 0x32, 0x41, 0xdd, 0xd2, 0x48,
	0x5a, 0xd7, 0xea, 0x6b, 0x07, 0x7d, 0x01, 0x5a, 0xe7, 0xa0, 0x1f, 0xf4, 0xc5, 0x8c, 0xf1, 0xd2,
	0x0f, 0xa6, 0xb3, 0x51, 0xb1, 0x08, 0x1e, 0xc6, 0x33, 0x6c, 0x28, 0xd6, 0x13, 0xf8, 0x7f, 0x18,
	0x93, 0xd5, 0xc7, 0x71, 0x8a, 0x09, 0xcb, 0x68, 0xca, 0x08, 0x32, 0x41, 0xcb, 0xcb, 0xf8, 0xe7,
	0xe0, 0x8b, 0xbc, 0xff, 0x55, 0x01, 0x75, 0xbe, 0x59, 0xa3, 0xc7, 0xd0, 0x18, 0x11, 0x2e, 0xf6,
	0xe4, 0xde, 0x6f, 0x7b, 0x6c, 0x1e, 0xea, 0xb0, 0x6a, 0x68, 0x00, 0xf7, 0x8f, 0xcf, 0x4a, 0xad,
	0x3f, 0xfd, 0xf5, 0x40, 0x42, 0x77, 0x8a, 0xb1, 0x6a, 0x97, 0x0a, 0xb2, 0xa1, 0x8d, 0xc9, 0x8a,
	0xe6, 0xeb, 0xc2, 0x5a, 0x64, 0xdc, 0xf5, 0xf9, 0x58, 0xb1, 0xa7, 0x44, 0x0d, 0xe9, 0xd8, 0xb3,
	0x1f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd7, 0x31, 0x4a, 0x73, 0xb5, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SidClient is the client API for Sid service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SidClient interface {
	// A simple RPC.
	//
	// Obtains the feature at a given position.
	//
	// A feature with an empty name is returned if there's no feature at the given
	// position.
	GetJob(ctx context.Context, in *HealthStatus, opts ...grpc.CallOption) (*Job, error)
	// A server-to-client streaming RPC.
	//
	// Streams health status of the client as it changes.
	HealthStatusCheckIn(ctx context.Context, in *HealthStatus, opts ...grpc.CallOption) (Sid_HealthStatusCheckInClient, error)
	// A client-to-server streaming RPC.
	//
	// Accepts a stream of JobRunEvents on a job being run, returning a
	// job when done.
	RecordJobRun(ctx context.Context, opts ...grpc.CallOption) (Sid_RecordJobRunClient, error)
}

type sidClient struct {
	cc *grpc.ClientConn
}

func NewSidClient(cc *grpc.ClientConn) SidClient {
	return &sidClient{cc}
}

func (c *sidClient) GetJob(ctx context.Context, in *HealthStatus, opts ...grpc.CallOption) (*Job, error) {
	out := new(Job)
	err := c.cc.Invoke(ctx, "/sid.Sid/GetJob", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sidClient) HealthStatusCheckIn(ctx context.Context, in *HealthStatus, opts ...grpc.CallOption) (Sid_HealthStatusCheckInClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Sid_serviceDesc.Streams[0], "/sid.Sid/HealthStatusCheckIn", opts...)
	if err != nil {
		return nil, err
	}
	x := &sidHealthStatusCheckInClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Sid_HealthStatusCheckInClient interface {
	Recv() (*CheckInResponse, error)
	grpc.ClientStream
}

type sidHealthStatusCheckInClient struct {
	grpc.ClientStream
}

func (x *sidHealthStatusCheckInClient) Recv() (*CheckInResponse, error) {
	m := new(CheckInResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sidClient) RecordJobRun(ctx context.Context, opts ...grpc.CallOption) (Sid_RecordJobRunClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Sid_serviceDesc.Streams[1], "/sid.Sid/RecordJobRun", opts...)
	if err != nil {
		return nil, err
	}
	x := &sidRecordJobRunClient{stream}
	return x, nil
}

type Sid_RecordJobRunClient interface {
	Send(*JobRunEvent) error
	CloseAndRecv() (*Job, error)
	grpc.ClientStream
}

type sidRecordJobRunClient struct {
	grpc.ClientStream
}

func (x *sidRecordJobRunClient) Send(m *JobRunEvent) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sidRecordJobRunClient) CloseAndRecv() (*Job, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Job)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SidServer is the server API for Sid service.
type SidServer interface {
	// A simple RPC.
	//
	// Obtains the feature at a given position.
	//
	// A feature with an empty name is returned if there's no feature at the given
	// position.
	GetJob(context.Context, *HealthStatus) (*Job, error)
	// A server-to-client streaming RPC.
	//
	// Streams health status of the client as it changes.
	HealthStatusCheckIn(*HealthStatus, Sid_HealthStatusCheckInServer) error
	// A client-to-server streaming RPC.
	//
	// Accepts a stream of JobRunEvents on a job being run, returning a
	// job when done.
	RecordJobRun(Sid_RecordJobRunServer) error
}

// UnimplementedSidServer can be embedded to have forward compatible implementations.
type UnimplementedSidServer struct {
}

func (*UnimplementedSidServer) GetJob(ctx context.Context, req *HealthStatus) (*Job, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJob not implemented")
}
func (*UnimplementedSidServer) HealthStatusCheckIn(req *HealthStatus, srv Sid_HealthStatusCheckInServer) error {
	return status.Errorf(codes.Unimplemented, "method HealthStatusCheckIn not implemented")
}
func (*UnimplementedSidServer) RecordJobRun(srv Sid_RecordJobRunServer) error {
	return status.Errorf(codes.Unimplemented, "method RecordJobRun not implemented")
}

func RegisterSidServer(s *grpc.Server, srv SidServer) {
	s.RegisterService(&_Sid_serviceDesc, srv)
}

func _Sid_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SidServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sid.Sid/GetJob",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SidServer).GetJob(ctx, req.(*HealthStatus))
	}
	return interceptor(ctx, in, info, handler)
}

func _Sid_HealthStatusCheckIn_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HealthStatus)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SidServer).HealthStatusCheckIn(m, &sidHealthStatusCheckInServer{stream})
}

type Sid_HealthStatusCheckInServer interface {
	Send(*CheckInResponse) error
	grpc.ServerStream
}

type sidHealthStatusCheckInServer struct {
	grpc.ServerStream
}

func (x *sidHealthStatusCheckInServer) Send(m *CheckInResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Sid_RecordJobRun_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SidServer).RecordJobRun(&sidRecordJobRunServer{stream})
}

type Sid_RecordJobRunServer interface {
	SendAndClose(*Job) error
	Recv() (*JobRunEvent, error)
	grpc.ServerStream
}

type sidRecordJobRunServer struct {
	grpc.ServerStream
}

func (x *sidRecordJobRunServer) SendAndClose(m *Job) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sidRecordJobRunServer) Recv() (*JobRunEvent, error) {
	m := new(JobRunEvent)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Sid_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sid.Sid",
	HandlerType: (*SidServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetJob",
			Handler:    _Sid_GetJob_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HealthStatusCheckIn",
			Handler:       _Sid_HealthStatusCheckIn_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RecordJobRun",
			Handler:       _Sid_RecordJobRun_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "sid.proto",
}
